### ISSUE TITLE
SVG output of points issue

### ISSUE THREAD

**Issue by adam-sampson** [marcocorvi/topodroid#22] opened 2016-10-23 21:19 UTC
Using Version 3.1.6i.

All points are placed at the origin of the viewbox, instead of at the point where they were actually placed. They show up as a blob and need to be replaced. 

Full file:
![svg point output](https://cloud.githubusercontent.com/assets/12676475/19629500/ac72a408-9944-11e6-8d8f-6e3cdf9b3847.png)

Zoomed into blob of point items:
![svg point output zoomed](https://cloud.githubusercontent.com/assets/12676475/19629502/b0888a4e-9944-11e6-9b3b-186bbfcb23ee.png)

Re-arranged to show the points that were in the blob:
![svg point output zoomed re-arranged](https://cloud.githubusercontent.com/assets/12676475/19629504/b3ae9858-9944-11e6-9ace-263f6da093c9.png)

**Comment by marcocorvi** [comment] 2016-10-24 08:36
could not reproduce this:
[1] points in the svg file have proper "translate"
[2] embedded in html the svg file displays points correctly in a browser

**Comment by marcocorvi** [comment] 2019-10-24 15:20
i could finally reproduce the issue with inkscape.
fixed in 4.1.4D

**Closed by marcocorvi** 2019-10-24 15:20 UTC
