### ISSUE TITLE
TopoDroid crashes when attempting to view a surface DEM

### ISSUE THREAD

**Issue by j-brewer** [marcocorvi/topodroid#47] opened 2022-10-10 01:16 UTC
**Describe the bug**
When attempting to toggle on the surface view of a .ASC surface (after the DEM is loaded), TopoDroid always crashes.

**To Reproduce**
1. Open a survey
2. Open the menu and select "3D"
3. Open the menu and select "Surface"
4. Select "Load DEM"
5. Choose a valid ASC DEM file
6. App returns to the 3D view with a message indicating "Read DEM Data"
7. Toggle the surface view button to the on state.
8. TopoDroid crashes

NOTE: No option is available to set a surface texture in the surface dialog.

**Expected behavior**
The 3D surface view should display.

**Device (please complete the following information):**
 - Samsung Galaxy TAB S2
 - Android version 7.0
 - TopoDroid version 6.1.56-33

**Additional context**

Relevant Stack Trace:
10-09 17:05:47.004 29146 29170 E AndroidRuntime: FATAL EXCEPTION: GLThread 3080
10-09 17:05:47.004 29146 29170 E AndroidRuntime: Process: com.topodroid.TDX, PID: 29146
10-09 17:05:47.004 29146 29170 E AndroidRuntime: java.lang.NullPointerException: texImage2D can't be used with a null Bitmap
10-09 17:05:47.004 29146 29170 E AndroidRuntime:        at android.opengl.GLUtils.texImage2D(GLUtils.java:149)
10-09 17:05:47.004 29146 29170 E AndroidRuntime:        at com.topodroid.TDX.GL.bindBitmap(GL.java:407)
10-09 17:05:47.004 29146 29170 E AndroidRuntime:        at com.topodroid.TDX.GL.bindTexture(GL.java:386)
10-09 17:05:47.004 29146 29170 E AndroidRuntime:        at com.topodroid.TDX.GlSurface.bindBitmap(GlSurface.java:175)
10-09 17:05:47.004 29146 29170 E AndroidRuntime:        at com.topodroid.TDX.GlSurface.draw(GlSurface.java:245)
10-09 17:05:47.004 29146 29170 E AndroidRuntime:        at com.topodroid.TDX.GlModel.draw(GlModel.java:361)
10-09 17:05:47.004 29146 29170 E AndroidRuntime:        at com.topodroid.TDX.GlRenderer.onDrawFrame(GlRenderer.java:596)
10-09 17:05:47.004 29146 29170 E AndroidRuntime:        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1562
)
10-09 17:05:47.004 29146 29170 E AndroidRuntime:        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1262)

**Comment by marcocorvi** [comment] 2022-10-10 04:47
thanks.

the error is caused by an attempt to draw the non-existing surface texture.
which the program should not do.

it will be fixed in the next version 6.1.66

**Closed** 2023-01-31 15:29 UTC
