### ISSUE TITLE
35 sdk Topodroid dies when opening a survey with Android 14

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#123] opened 2024-07-30 10:59 UTC
**Describe the bug**
35 sdk Topodroid dies when opening a survey with Android 14

**To Reproduce**
1. Install any 35 SDK Topodroid version 
2. Try to open any existing survey or create a new survey
4. See Topodroid closing immediately

**Expected behavior**
Newer Topodroid should work on Android 14 with SDK 34. Up to version 6.2.75 everything is fine. 

**Device:**
 - Samsung 23FE
 - Android 14
 - TopoDroid 6.2.82

**Comment by marcocorvi** [comment] 2024-07-30 11:11
write permission ?

**Comment by marcocorvi** [comment] 2024-07-30 12:33
i cannot check android 14.
therefore the issue is assigned to R. Severo

**Comment by rsevero** [comment] 2024-08-01 16:51
I believe commit [b4e6c26](https://github.com/marcocorvi/topodroid/commit/b4e6c26c0228e928c08e0700efa8c41f22f0a143) fixed this issue.

I am not entirely sure as I can't create a proper update and try it on my phone.

For a completely new installation, survey opening and creation are working again.

**Comment by marcocorvi** [comment] 2024-08-01 19:16
indeed there was a typo in the table create.
it made the table create fails so the DB had no tables.

this solves the issue of topodroid not listing the paired devices
(they could not be inserted in the DB)

however, surveys are in a different DB.

**Comment by marcocorvi** [comment] 2024-08-01 19:30
oops, i was correcting a similar error in the device DB,
i realized you already corrected the one in the survey DB.

yes, now the issue is fixed

**Comment by marcocorvi** [comment] 2024-08-01 19:35
fixed and fixed also the failure to list distox

**Closed by marcocorvi** 2024-08-01 19:35 UTC

**Comment by rsevero** [comment] 2024-08-02 15:56
My local installation had no "reftype" columns despite being on DB version 54. I had to manually add them.

I believe commit 967e72ee2 will fix this automatically for other users that might be in the same situation I was.

**Comment by marcocorvi** [comment] 2024-08-02 19:00
i saw the commit.

On Fri, Aug 2, 2024, 17:56 Rodrigo Severo ***@***.***> wrote:

> My local installation had no "reftype" columns despite being on DB version
> 54.
>
how did that happened ?

> I had to manually add them.
>
> I believe commit 967e72e
> <https://github.com/marcocorvi/topodroid/commit/967e72ee2d95d1233f572454e7dc8a3a0942ada4>
> will fix this automatically for other users that might be in the same
> situation I was.
>
how could that happen ?

**Comment by rsevero** [comment] 2024-08-02 20:39
I am not sure. I tried almost all version between 6.2.75 and 6.2.84. I started having problems with the first version you mentioned "SDK 35 test".

To make TopoDroid work again I had to go back to 6.2.75 until now when I manually added the "reftype" field in the 3 media tables to use my regular data. When I did a clean install everything was working just fine.

Unfortunatelly I didn't check each version to understand exactly how this could have happened.

commit https://github.com/marcocorvi/topodroid/commit/967e72ee2d95d1233f572454e7dc8a3a0942ada4 is not pretty but prevents users getting stuck at version 6.2.75 as I were.

Please fill free to undo it if it looks too ugly.

**Comment by marcocorvi** [comment] 2024-08-03 03:48
i get an error message about duplicate column name.
apparently it has no effect, but we will take care of that later.

**Comment by rsevero** [comment] 2024-08-03 10:21
> i get an error message about duplicate column name. apparently it has no effect, but we will take care of that later.

Fixed with commit 68df32996.

Sorry for the confusion.
