### ISSUE TITLE
Short bezier lines disappears after being drawn

### ISSUE THREAD

**Issue by rsevero** [marcocorvi/topodroid#90] opened 2024-01-30 01:12 UTC
**Describe the bug**
For many line types, short bezier lines are not drawn

**To Reproduce**
1. Set bezier line type
2. Try to draw a short line
3. See that it is drawn but disappears

**Expected behavior**
Drawn lines should not disappear

**Screenshots**
[Video showing the issue](https://we.tl/t-uYiZbNlxm5)

**Device (please complete the following information):**
 - Motorola g42
 - Android 13
 - TopoDroid v 6.2.46

**Additional context**
Rock edge lines does not disappear even when drawn short as the others as it can be seen on the video.

**Comment by marcocorvi** [comment] 2024-01-30 06:33
fixed in v. 6.2.47

the cause was a test <= instead of < in bezier()

**Closed by marcocorvi** 2024-01-30 06:33 UTC
